### ISSUE TITLE
super().__init__() giving problems

### ISSUE THREAD

**Issue by thebhatman** [philgooch/abbreviation-extraction#15]
https://github.com/philgooch/abbreviation-extraction/blob/f163bac79efdff52af7ba3f5ce47def56b0f5b43/abbreviations/schwartz_hearst.py#L24
Here, I faced an error saying super().__init__() takes one argument, 0 given.
However, the issue was resolved and it worked when I removed this line. I am working with Python 2.7.

**Comment by philgooch** [comment]
Hi @thebhatman , thanks for this. The codebase is Python 3 only, so it may not work with Python 2.7. Glad you got it working!
