### ISSUE TITLE
Is there any example

### ISSUE THREAD

**Issue by Crescentz** [philgooch/abbreviation-extraction#16]
if i want to extract introduction from a science-papper ,  is there a nice tool?

**Comment by aolieman** [comment]
This package/algorithm can be used for abbreviation extraction. What you are asking seems out of scope.

After you manage to extract the introduction, this package can of course be very helpful in extracting abbreviations from it.

**Comment by philgooch** [comment]
@Crescentz there are a few tools you can try that work will extract sections from research paper PDFs:

- https://github.com/allenai/science-parse
- https://github.com/kermitt2/grobid
- https://github.com/CeON/CERMINE
