### ISSUE TITLE
Condition redundant

### ISSUE THREAD

**Issue by atharvakadlag** [philgooch/abbreviation-extraction#26]
https://github.com/philgooch/abbreviation-extraction/blob/2e334bbe474a4030c07860839c023775bb97c4ae/abbreviations/schwartz_hearst.py#L112-L140

https://github.com/philgooch/abbreviation-extraction/blob/2e334bbe474a4030c07860839c023775bb97c4ae/abbreviations/schwartz_hearst.py#L129

The above condition is unused, the condition being true or false has no effect on the variable "viable"

**Comment by philgooch** [comment]
Thanks - fixed by #27
