### ISSUE TITLE
Release on PyPI?

### ISSUE THREAD

**Issue by micahjsmith** [philgooch/abbreviation-extraction#29]
You've already done the hard work of cutting releases to GitHub releases. It would make it easier to install if it could be released to PyPI as well. I'm happy to help out with this with your blessing

**Comment by philgooch** [comment]
Hi @micahjsmith thanks for contributing. I released on PyPI a long time ago: https://pypi.org/project/abbreviations/

I need to update with a new release soon.

**Comment by micahjsmith** [comment]
awesome! no action needed then

**Comment by philgooch** [comment]
@micahjsmith I can add you as a maintainer for this project if you like

**Comment by micahjsmith** [comment]
sure, I'm happy to help out. in case you ever need to reach me offline: https://www.micahsmith.com/contact/
